apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
   name: defaultfunc
spec:
   broker: default
   filter:
      attributes:
         type: defaultFunc
   subscriber:
      ref:
         apiVersion: serving.knative.dev/v1
         kind: Service
         name: function-knative-events